on:
  pull_request:
    paths: 'src/**'

concurrency:
  group: benchmark
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: cargo install --locked hyperfine
      - run: make FLAG=-DPIC2ASCII_RELEASE
      - run: |
          {
            echo -e 'to STDOUT\n'
            echo '```'
            hyperfine './bin/main input/sample.png --block_width=16'
            echo '```'
            echo -e '\n---\n'
          } >> /tmp/comment.txt
      - run: |
          {
            echo -e 'to STDOUT\n'
            echo '```'
            hyperfine './bin/main input/sample.png --block_width=32'
            echo '```'
            echo -e '\n---\n'
          } >> /tmp/comment.txt
      - uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: from-actions-comment-pull-request
          filePath: /tmp/comment.txt
