on:
  push:

jobs:
  make-run:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: make run
  make-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: make test
  make-stats:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: make stats
