on:
  push:
    branches:
      - main

jobs:
  update-sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - run: make
      - run: |
          ./bin/main ./input/sample.png ./output/sample.png --block_width=8
      - uses: peter-evans/create-pull-request@v5
        with:
          branch: update-sample/${{ github.ref_name }}
